In [2]:
import numpy as np
!mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.755 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd

In [16]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [17]:
data['b']

np.float64(0.5)

In [18]:
'a' in data

True

In [19]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='str')

In [20]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [21]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [22]:
# Slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [23]:
# Slicing by explicit integer index
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [24]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [26]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [27]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [28]:
data

1    a
3    b
5    c
dtype: str

In [29]:
print(data[1])
print(data[1:3])

a
3    b
5    c
dtype: str

In [30]:
data.loc[1]

'a'

In [31]:
data.loc[1:3]

1    a
3    b
dtype: str

In [32]:
data.iloc[1]

'b'

In [33]:
data.iloc[1:3]

3    b
5    c
dtype: str

In [34]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area': area, 'pop': pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [35]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [36]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [38]:
data.area == data['area']

California    True
Texas         True
New York      True
Florida       True
Illinois      True
Name: area, dtype: bool

In [39]:
data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [40]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [41]:
data.T

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [42]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [43]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
data.iloc[:3, :2]

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [45]:
data.loc[: 'New York', : 'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [48]:
data.loc[data.density > 100, ['pop', 'density']]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [49]:
data.iloc[0, 2] = 90
data

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763